#!/usr/bin/env python3
"""
gen_manifest.py — (re)generate image/MANIFEST.json: {relative path -> sha256} for every file
in image/ (except the manifest itself), plus the image version. The manifest is what a
bootstrap copies into an instance as its OS-MANIFEST.lock, and what UPGRADE.md three-way
diffs against — so it must be exact and committed fresh with every image change (CI enforces
via --check).

  python3 scripts/gen_manifest.py            # write image/MANIFEST.json
  python3 scripts/gen_manifest.py --check    # exit 1 if the committed manifest is stale
"""
import hashlib, json, os, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG = os.path.join(ROOT, "image")
MANIFEST = os.path.join(IMG, "MANIFEST.json")


def build():
    files = {}
    for dirpath, dirnames, filenames in os.walk(IMG):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith(".") and d != "__pycache__")
        for fn in sorted(filenames):
            if fn.startswith(".") or fn.endswith((".pyc", ".pyo")):
                continue
            p = os.path.join(dirpath, fn)
            r = os.path.relpath(p, IMG).replace(os.sep, "/")
            if r == "MANIFEST.json":
                continue
            with open(p, "rb") as f:
                files[r] = hashlib.sha256(f.read()).hexdigest()
    version = open(os.path.join(IMG, "VERSION"), encoding="utf-8").read().strip()
    return {"_what": "documentation-as-os image manifest — generated by scripts/gen_manifest.py; "
                     "do NOT hand-edit. Bootstraps copy this into the instance as OS-MANIFEST.lock.",
            "version": version, "files": files}


def main():
    fresh = build()
    if "--check" in sys.argv:
        try:
            committed = json.load(open(MANIFEST, encoding="utf-8"))
        except Exception:
            print("MANIFEST-FRESH: image/MANIFEST.json missing or unreadable — run scripts/gen_manifest.py and commit it")
            return 1
        if committed.get("files") != fresh["files"] or committed.get("version") != fresh["version"]:
            diff = [k for k in sorted(set(committed.get("files", {})) | set(fresh["files"]))
                    if committed.get("files", {}).get(k) != fresh["files"].get(k)]
            print(f"MANIFEST-FRESH: image/MANIFEST.json is stale ({len(diff)} entries: "
                  f"{', '.join(diff[:3])}{'…' if len(diff) > 3 else ''}"
                  f"{'; version drift' if committed.get('version') != fresh['version'] else ''}) "
                  f"— run scripts/gen_manifest.py and commit it")
            return 1
        print(f"manifest fresh ({len(fresh['files'])} files, image {fresh['version']})")
        return 0
    fresh["_generated"] = datetime.date.today().isoformat()
    with open(MANIFEST, "w", encoding="utf-8") as f:
        json.dump(fresh, f, indent=1, ensure_ascii=False)
        f.write("\n")
    print(f"image/MANIFEST.json written ({len(fresh['files'])} files, image {fresh['version']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
